package com.woniuxy.demo.model;

public class Roletree extends RoletreeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roletree.rule
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    private String rule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roletree.rule
     *
     * @return the value of roletree.rule
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roletree.rule
     *
     * @param rule the value for roletree.rule
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }
}