package com.woniuxy.demo.model;

public class Tree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.id
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    private Integer id;
    private boolean open = true;

    public boolean isOpen() {
        return open;
    }

    public void setOpen(boolean open) {
        this.open = open;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.name
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.file
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    private String file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.pid
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.id
     *
     * @return the value of tree.id
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.id
     *
     * @param id the value for tree.id
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.name
     *
     * @return the value of tree.name
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.name
     *
     * @param name the value for tree.name
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.file
     *
     * @return the value of tree.file
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.file
     *
     * @param file the value for tree.file
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.pid
     *
     * @return the value of tree.pid
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.pid
     *
     * @param pid the value for tree.pid
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}