package com.woniuxy.demo.mapper;

import com.woniuxy.demo.model.Roletree;
import com.woniuxy.demo.model.RoletreeExample;
import com.woniuxy.demo.model.RoletreeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoletreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    int countByExample(RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    int deleteByExample(RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    int deleteByPrimaryKey(RoletreeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    int insert(Roletree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    int insertSelective(Roletree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    List<Roletree> selectByExample(RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    Roletree selectByPrimaryKey(RoletreeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") Roletree record, @Param("example") RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    int updateByExample(@Param("record") Roletree record, @Param("example") RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    int updateByPrimaryKeySelective(Roletree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue May 26 21:56:53 CST 2020
     */
    int updateByPrimaryKey(Roletree record);
}